# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64 # 64-bit x86 (Intel/AMD) - Most common for servers and PCs.
      - arm64 # 64-bit ARM (Apple Silicon M1/M2/M3, AWS Graviton, Raspberry Pi 4).
      #- arm   # 32-bit ARM (Legacy Raspberry Pi 1/2/3).
      #- 386   # 32-bit x86 (Intel/AMD) - Common on legacy systems and some embedded devices.
    ldflags:
      - -s -w
      - -X github.com/activebook/gllm/cmd.version={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# ---- HOMEBREW INTEGRATION ----
brews:
  - name: gllm # Name of the formula file (gllm.rb)
    # Repository details for your Homebrew tap
    repository:
      owner: activebook # Your GitHub username/org
      name: homebrew-gllm # The name of your tap repo (e.g., homebrew-gllm)
      # Optional: Branch to push to (defaults to 'main' or 'master')
      # branch: main
      # Optional: Token to push to the tap repository
      # Set GITHUB_TOKEN environment variable for this. It needs repo scope.
      # token: "{{ .Env.GITHUB_TOKEN }}"

    # GoReleaser will automatically set homepage, url, sha256, and version.
    # You can override or add fields:
    description: "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs). Configure your API keys, set your preferred models, and start chatting or executing commands effortlessly."
    license: "Apache-2.0" # e.g., MIT

    # Optional: Add dependencies
    # dependencies:
    #   - name: "bash"
    #   - name: "zsh"
    #     type: "optional"

    # Optional: Specify installation steps if default isn't enough
    # (Usually not needed when GoReleaser handles binaries)
    # install: |
    #   bin.install "gllm"
    #   # Add commands to install other things like man pages, completions, etc.
    #   # man1.install "man/gllm.1"
    #   # bash_completion.install "completions/gllm.bash" => "gllm"

    # Optional: Add test block
    test: |
      system "#{bin}/gllm --version"

    # Commit message customization
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

# Optional: Scoop integration (for Windows users)
scoop:
  bucket:
    owner: activebook  # Your GitHub username/org
    name: scoop-gllm   # Name of your Scoop bucket repo (create this repo if it doesn't exist)
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/activebook/gllm"
  description: "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs). Configure your API keys, set your preferred models, and start chatting or executing commands effortlessly."
  license: "Apache-2.0"
