version: 2

before:
  hooks:
    # Ensure the Go module dependencies are up to date and tidy before building.
    - go mod tidy

builds:
  - env:
    # Tell the Go toolchain to disable cgo, which means it will not use any C code or link against C libraries (like glibc) during the build process.
    # The result is a statically linked binary that contains all its necessary code within a single file.
      - CGO_ENABLED=0
    goos:
    # Target operating systems for the build.
      - linux
      - windows
      - darwin
    goarch:
      - amd64 # 64-bit x86 (Intel/AMD) - Most common for servers and PCs.
      - arm64 # 64-bit ARM (Apple Silicon M1/M2/M3, AWS Graviton, Raspberry Pi 4).
      #- arm   # 32-bit ARM (Legacy Raspberry Pi 1/2/3).
      #- 386   # 32-bit x86 (Intel/AMD) - Common on legacy systems and some embedded devices.
    ldflags:
      # -s flag omits the symbol table and debug information from the compiled binary.
      # -w flag omits the DWARF debugging information.
      - -s -w
      # -X flag sets a variable in the compiled binary.
      - -X github.com/activebook/gllm/cmd.version={{.Version}}

archives:
  - formats: [tar.gz] # Fix: Changed from format to formats
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip] # Fix: Changed from format to formats

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# ---- HOMEBREW INTEGRATION ----
# https://brew.sh/
# Build a Homebrew formula for macOS users.
homebrew_casks:
  - name: gllm
    repository:
      owner: activebook
      name: homebrew-gllm
    description: "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs)."
    license: "Apache-2.0"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

# ---- SCOOP INTEGRATION ----
# https://scoop.sh/
# Build a Scoop package for windows users.
scoops:
  - name: gllm
    repository:
      owner: activebook  
      name: scoop-gllm   
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/activebook/gllm"
    description: "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs)."
    license: "Apache-2.0"

# ---- Linux INTEGRATION ----
# Linux users can install via install.sh script.