version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64 # 64-bit x86 (Intel/AMD) - Most common for servers and PCs.
      - arm64 # 64-bit ARM (Apple Silicon M1/M2/M3, AWS Graviton, Raspberry Pi 4).
      #- arm   # 32-bit ARM (Legacy Raspberry Pi 1/2/3).
      #- 386   # 32-bit x86 (Intel/AMD) - Common on legacy systems and some embedded devices.
    ldflags:
      - -s -w
      - -X github.com/activebook/gllm/cmd.version={{.Version}}

archives:
  - formats: [tar.gz] # Fix: Changed from format to formats
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip] # Fix: Changed from format to formats

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# ---- HOMEBREW INTEGRATION ----
homebrew_casks:
  - name: gllm
    repository:
      owner: activebook
      name: homebrew-gllm
    description: "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs)."
    license: "Apache-2.0"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

# ---- SCOOP INTEGRATION ----
scoops:
  - name: gllm
    repository:
      owner: activebook  
      name: scoop-gllm   
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/activebook/gllm"
    description: "`gllm` is a powerful command-line tool designed to interact seamlessly with various Large Language Models (LLMs)."
    license: "Apache-2.0"