services:
  # Run the gllm service using the local Dockerfile or a pre-built image
  gllm:
    # Build using the Dockerfile in the current directory(for local)
    # build: .
    
    # Local image
    #image: gllm:latest

    # Downloaded remote package
    image: ghcr.io/activebook/gllm:latest

    # Mount the current folder to /home/gllmuser inside the container
    volumes:
      # Per-project config — each folder has its own gllm.yaml, sessions, skills:
      - .:/home/gllmuser
      # Global config — all sessions, configs, and skills in one place:
      # - ~/.config/gllm:/home/gllmuser/.config/gllm
    
    # Enable modern color support
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
      # Proxy settings (if needed, adjust the proxy URL and port accordingly)
      #- HTTP_PROXY=http://host.docker.internal:7890
      #- HTTPS_PROXY=http://host.docker.internal:7890
      #- http_proxy=http://host.docker.internal:7890
      #- https_proxy=http://host.docker.internal:7890
    
    # For linux
    #network_mode: host
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

    # Keep the terminal open for interactive commands
    stdin_open: true
    tty: true
  
  # Run a ttyd service to access the gllm terminal interface via a web browser
  # local image for ttyd, for debugging and development
  gllmd:
    image: gllm:latest
    volumes:
      - .:/home/gllmuser
    # Enable modern color support
    environment:
      - TERM=xterm-256color
      - COLORTERM=truecolor
    ports:
      #- "8080:8080"  # Map your computer's 8080 to the container's 8080
      - "9000:9000"  # For gllm's web UI if it uses port 9000
    # Optional: ensure it runs the command correctly
    entrypoint: ["/usr/bin/ttyd"]  # Override the gllm entrypoint    
    #command: ["-W", "-p", "9000", "gllm"]
    command: ["-W", "-p", "9000", "sh"]

    # How to run ttyd:
    # 1. Start the ttyd service: `docker compose run --rm --service-ports gllmd`
    # 2. Open your browser and navigate to http://localhost:9000 to access the terminal interface.
    # Note: If you want to run ttyd in the foreground for debugging 
    # you must explicitly tell Docker to enable the port mappings
